Bump Dependencies. Expo SDK 40 / React Native 0.63
akveo/kittenTricks pull request #316
Opened 2021-02-15 08:13 UTC by artyorsh

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/kittenTricks/blob/master/CONTRIBUTING.md) guide.

 #### Short description of what this resolves:
 
 Closes #306

2021-03-02 09:20 UTC, malashkevich approved these changes

2021-03-02 09:56 UTC, whitestranger7 commented
There's an issue with expo web loading. After `app-loading.component.expo` change, web load crashes with erorr:

<img width="1069" alt="Screenshot 2021-03-02 at 12 45 59" src="https://user-images.githubusercontent.com/36364993/109631080-ae809b80-7b56-11eb-8867-f2b0f7acf4ab.png">

2021-03-05 07:52 UTC, malashkevich commented on src/app/app-loading.component.expo.tsx
> +  const onTasksFinish = React.useCallback((): void => {
I don't think you need `useCallback ` here

2021-03-05 07:53 UTC, malashkevich commented on src/app/app-loading.component.expo.tsx
> +      ...props.tasks.map(task => task().then(saveTaskResult)),
map already returns an array

2021-03-05 07:55 UTC, malashkevich commented on tsconfig.json
> -    "paths": {
this block should stay I guess

2021-03-05 07:56 UTC, malashkevich requested changes
Please make sure kitten tricks works properly with local UI kitten

2021-03-18 06:24 UTC, merged